### ISSUE TITLE
Want to join SDS

### ISSUE THREAD

**Issue by niteshJyo** [SDS-Society-for-Data-Science-BIT-Mesra/New-Comers#18]
Hey there! I am from BIT Mesra ( Jaipur Campus ) BE-CSE (3rd year). I would love to be a part of SDS,BIT Mesra  and wanto contribute 😄 kindly add me to the organisation.

**Comment by RohitRathore1** [comment]
@niteshJyo Thanks for showing your interest. Surely, we would love to have you on board.

**Comment by niteshJyo** [comment]
Thanks
